

export enum CONFIG_KEYS {
    PORT = 'PORT',
    DATABASE_URL = 'DATABASE_URL',
    NODE_ENV = 'NODE_ENV',
    JWT_SECRET = 'JWT_SECRET',
    JWT_EXPIRES_IN = 'JWT_EXPIRES_IN',
    JWT_REFRESH_SECRET = 'JWT_REFRESH_SECRET',
    JWT_REFRESH_EXPIRES_IN = 'JWT_REFRESH_EXPIRES_IN',
    TTL_TIME = 'TTL_TIME',
    THROTTLE_LIMIT = 'THROTTLE_LIMIT',
    FRONTEND_URL = 'FRONTEND_URL'
}