

export enum CONFIG_KEYS {
    PORT = 'PORT',
    DATABASE_URL = 'DATABASE_URL',
    NODE_ENV = 'NODE_ENV',
    JWT_SECRET = 'JWT_SECRET',
    JWT_EXPIRES_IN = 'JWT_EXPIRES_IN',
    JWT_REFRESH_SECRET = 'JWT_REFRESH_SECRET',
    JWT_REFRESH_EXPIRES_IN = 'JWT_REFRESH_EXPIRES_IN',
    TTL_TIME = 'TTL_TIME',
    THROTTLE_LIMIT = 'THROTTLE_LIMIT',
    FRONTEND_URL = 'FRONTEND_URL',

    MAIL_HOST = 'MAIL_HOST',
    MAIL_PORT = 'MAIL_PORT',
    MAIL_USER = 'MAIL_USER',
    MAIL_PASSWORD = 'MAIL_PASSWORD',
    MAIL_FROM = 'MAIL_FROM'

}